# Predefined dictionary of corporate jargon, buzzwords, and clichés.
# These will be matched case-insensitively.

CLICHES = [
    "highly motivated",
    "results-oriented",
    "synergistic alignment",
    "results-driven leader",
    "go-getter",
    "think outside the box",
    "thinking outside the box",
    "dynamic team player",
    "strategic thinker",
    "proven track record",
    "value-add",
    "leverage resources",
    "deep dive",
    "circle back",
    "synergy",
    "synergies",
    "paradigm shift",
    "empower employees",
    "actionable insights",
    "touch base",
    "win-win",
    "seamless integration",
    "cutting-edge",
    "world-class",
    "best-in-class",
    "innovative solutions",
    "disruptive innovation",
    "agile methodology",
    "cross-functional collaboration",
    "moving the needle",
    "low-hanging fruit",
    "core competency",
    "wheelhouse",
    "thought leader",
    "best practices",
    "scale up",
    "bandwidth",
    "on the radar",
    "results-oriented matrix",
    "to whom it may concern",
    "game changer",
    "leverage",
    "optimize",
    "utilize",
    "streamline",
    "robust",
    "empower",
    "impactful",
    "next generation",
    "revolutionary",
    "passionate professional",
    "detail-oriented",
    "self-starter",
    "team player",
    "highly qualified"
]
